### ISSUE TITLE
cd_text 'stop' is mixed inclusive/exclusive?

### ISSUE THREAD

**Issue by nsaphra** [csinva/hierarchical-dnn-interpretations#3]
while going through the code, I noticed on line 90 of `scores.py`:

```python
if i >= start and i <= stop:
```

That is, the set of relevant tokens is inclusive of the token at `stop`. But on line 108, adding the bias activations to the relevant component:

```python
if i >= start and i < stop:
```

So the bias is treated differently, with `stop` being exclusive for the bias but inclusive for the propagated inputs. Why is this? I didn't see anything in the paper that indicated that the propagated bias and input are treated differently.

**Comment by csinva** [comment]
Thanks for catching this! You're right there is no reason for this and both lines should in fact be `if i >= start and i <= stop:`.

Luckily this had hardly any effect on the SST model we used, but could certainly be important for other models / datasets! 

I've just fixed this and added better docstrings to this file.
