### ISSUE TITLE
Explanation of this method and features on Regression Problem

### ISSUE THREAD

**Issue by pidahbus** [csinva/hierarchical-dnn-interpretations#5]
Hi,

Assume I want to apply this method on a NLP regression problem: Prediction of a score given some answer scripts. In this scenario, let's assume that this phrase: "it was very good" has a very positive CD score. Does it mean that the inclusion of the above phrase in the answer increases the predicted score and vice versa? 

Can the similar kind analogy be drawn for a phrase having negative CD score i.e. inclusion of that phrase will decrease the score of the answer.

**Comment by csinva** [comment]
Yes that is the intuition for what it does! (i.e. the score of the phrase is the contribution of the phrase to the prediction).
